### ISSUE TITLE
External 7.6v supply.

### ISSUE THREAD

**Issue by DieKatzchen** [ShendoXT/memcarduino#10]
Is it actually necessary for it to be external or can I use a boost convertor?

**Comment by TheBlueTroll** [comment]
technically, for a standard psx memory card the 7.6 isnt connected, for third party cards maybe, but Sony ones dont have it connected on the card itself. so no, its usually not necessary.

**Comment by TheBlueTroll** [comment]
dunno, i mean its incredibly dependent on what the third party card maker used the 7.6 rail for. 
i assume sony initially added the 7.6 volt rail on the memcard port for eeprom erasure (eeprom needed higher voltages to erase) but then sony changed official cards to flash which didn't need the higher voltage.
Its not used by sony so i don't know how hard the requirement of 7.6 is, expesially with third party cards being literally whatever the manufactorers decided was ok. try a boost converter and see how it goes.

**Comment by DieKatzchen** [comment]
Looking at my card collection, I only have one unofficial card and it doesn't use that line (I checked). Debating whether I should acquire an unofficial card so I can test it or just leave well enough alone.

**Comment by TheBlueTroll** [comment]
Honestly i dont think its worth the effort because i also have alot of trouble even finding third party cards around where i am, and even then who knows how many used the 7.6v line anyway.

**Comment by DieKatzchen** [comment]
If I have to I can pull out my ps3 memory card thingy and run mcrwin in a virtual Windows xp
