### ISSUE TITLE
3rd party multipage memcard help

### ISSUE THREAD

**Issue by kichro** [ShendoXT/memcarduino#14]
Hi, 
first I'd like to thank you for your effort. I successfully repurposed a 3rd party PS2 to PS3 memcard reader to a memCARDuino with an Arduino Mini board. It even fits in the case nicely. 

https://imgur.com/a/kUTLzUV

So naturally I went and read all my old PS1 memory cards(all are 3rd party) with no problems. However, one of my 3rd party memcards has two pages which in normal conditions can be switched with a controller input(SELECT+R1). So, I've figured, since PS1 controllers and memcards use same bus and same pins with a similar communication sequence, it should be possible to emulate pressing those buttons on memCARDuino. Apparently, multipaged memcards listen on the bus for that controller input. I've already tried passing the controller-side of the communication sequence to the DATA pin of the memory card using your code but with no success.

Can you please offer me some advice regarding the issue?

Reference I used: http://problemkaputt.de/psx-spx.htm#controllerscommunicationsequence

Thank you in advance.

**Comment by TheBlueTroll** [comment]
Soo, this is going to be trickybut in short, there are 2 unidirectional data buses for memory card (and by extension controllers) mosi (master out slave in) and miso (master in slave out). The mcduino uses mosi to talk to controllers and to the mc, and the controller or mc use the other miso to talk back. You need to fake controller inputs on the other line for that to work. If you have a ps1 controller and you wire up a full controller port in addition to the memory card, it could be done with a couple little software changes.
 Faking a second spi device with just the memcarduino is probably not possible, as we already use hardware in the arduino to communicate.
Sorry for the long delay, i really need to check my emails more often.
