### ISSUE TITLE
Official playstation 2 memory cardmagic gate 8mb

### ISSUE THREAD

**Issue by dimitrisKarampistis** [ShendoXT/memcarduino#15]
I have followed every instruction on the readme file however it does not seem to working I am using the exe application and it is saying that memory card is not connected. I have checked everything with a multimeter and everything is fine, the card is working I mean the ps2 can access it normally I have tried a testfile .ino and the serial out it just a bunch of F... I have installed the right drivers and I have compiled and the sent the file to and arduino uno, I still can not get it to work

**Comment by TheBlueTroll** [comment]
The memcarduino doesnt support ps2 cards due to the magicgate encryption system used on them. It only supports the original playstation's memory card.

**Comment by frytkisasmaczne** [comment]
do you think it would work on what i think is a chinese knockoff of a ps2 mc?
![Uploading 20200125_152557.jpg…]()

**Comment by eshicks4** [comment]
without magicgate the ps2 won't even talk to the card so even knockoffs will need to include it
