### ISSUE TITLE
Mention pyserial in the README

### ISSUE THREAD

**Issue by eshicks4** [ShendoXT/memcarduino#21]
You may want to mention in the README.md that they need to 'pip install pyserial' for the PC-side script.  Otherwise there are interpreter errors.  There's also a pip package which is just called 'serial' (probably a dep of pyserial) which adds to the confusion by fixing the import but then failing again later during the instantiation.

Other than that everything "just worked" so many thanks!

**Comment by ShendoXT** [comment]
Added to the readme, thanks for the heads-up.
