### ISSUE TITLE
Unclear pinout in Readme

### ISSUE THREAD

**Issue by SpankyToot** [ShendoXT/memcarduino#27]
Just dropping this here, the pinout is unclear as its listing pin numbers but referring to pin names.
Here is my suggested edit to make it easier for future users.

Mem Pin 1:	DATA - Pin 15 - D12 on Arduino
Mem Pin 2:	CMND - Pin 14 - D11 on Arduino
Mem Pin 3:	7.6V - From external source for cheap copy cards (Not normally needed)
Mem Pin 4:	GND -  Pin 29 - GND on Arduino
Mem Pin 5:	3.6V - Pin 27 - +5V on Arduino (Use a voltage divider if concerned about Genuine cards)
Mem Pin 6:	ATT - Pin 13 - D10 on Arduino
Mem Pin 7:	CLK - Pin 16 - D13 on Arduino
Mem Pin 8:	ACK - Pin 5 - D2 on Arduino

Thank you for this awesome project.

**Comment by ShendoXT** [comment]
Thanks for the heads-up, I changed the readme, hope it's good now.
