### ISSUE TITLE
Can't detect new release with nano v3

### ISSUE THREAD

**Issue by carmax91** [ShendoXT/memcarduino#29]
Hi Shendo,
I've updated my memcarduino with the latest release (0.6) but memcardrex fails to detect my nano v3 with atmega328p either with the newest and old memcardrex release...
If i try to read my mc, memcardRex don't detect the memcarduino on the selected COM port.
Reverted to the old release (0.5) it works again only with old memcardrex version (so it is not an hw issue). On the latest MemcardRex the memcarduino is not detected either with default and legacy speed.

Seems the sketch is bugged with 328p variants...

**Comment by ShendoXT** [comment]
Hm, try using older MemcardRex with MemCARDuino v0.6 but drop the speed to 38400 manually in the sketch.
I have a feeling that while adding the option to toggle DTR line for Leonardo in newest MemcardRex broke the support for atmega328, sigh...

**Comment by carmax91** [comment]
Nothing Shendo. Still Broken!

**Comment by ShendoXT** [comment]
Oh, must be MemcardRex then, I'll focus my attention on it to solve this issue. Thanks for the info.
I saw you sent me a PM on discord, if you want I can send you updated MemcardRex so you can test it before I release it.

**Comment by ShendoXT** [comment]
New MemcardRex release which fixes this issue is live, closing this issue.
