### ISSUE TITLE
ESP32 and ESP8266: "mc read failure, check connections", printed data displays evidence of card data being read

### ISSUE THREAD

**Issue by padraigfl** [ShendoXT/memcarduino#33]
I've tried this on both an ESP32 (38 pin dev board) and ESP8266 (Wemos D1) with the same results for both. MemcardRex is picking up the board as 0.6 but is immediately stalling.

Having ran the Python script ( `python3 .\memcarduino.py -p COM4 -r data.txt` ) it outputs the following:

```
running mcduino check
b'reading\r\nQ\x00\x00\x00\x00 \x00\x00\xff\xffBESLES-03575\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'\x00'
Response Byte is:

b'\x00'
error: mc read failure, check connections
```

The SLES-03575 game code refers to one of the games I know is on the memory card so it does seem to be reading _something_, changing the line `ser.write(MCR + b"\x00\x01")` appears to be iterating through the files in the memory card from the game codes.

I've tried two memory cards (one official, one not) and gotten the same results on both boards.

The memory card port is one zombied together from a broken multi-tap, I've tried multiple of the ports from the multi tap 

I've ordered an Arduino Nano and will try it out too when it arrives, but if there's anything else I can debug here I'd appreciate knowing it.

**Comment by ShendoXT** [comment]
Try using pull-ups. Put 1K external pull-up resistors to 3.3V on Cmd, Data, Att, Clk and Ack lines.

**Comment by padraigfl** [comment]
Thanks for the very quick response! Tried that with both devices, unfortunately only got:

```
running mcduino check
b'reading\r\n\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
b'\xff'
Response Byte is:

b'\xff'
error: mc read failure, check connections
```

There's a decent chance it was something to do with the suboptimal setup I have at the moment rather than anything else though.

Will try the Nano when it arrives next week and report back 👍

**Comment by ShendoXT** [comment]
One thing to note since you said that you are using ports on the multitap. Are the ports still connected to the logic board? It might be interfering with the connection...

**Comment by padraigfl** [comment]
Ooof, my bad, I was looking into the ESP code and noticed I left some log stuff in the `.ino` file that was throwing everything off (you can see it above in the response with "reading"). Can confirm the Wemos D1 board works and I can't see why the ESP32 wouldn't work equally well. Will close this issue.

I most likely had some kind of wiring issue initially and broke the file.

Thanks for the help and the project overall, saves me from having to buy a PS2 for some PocketStation experiments I want to do!

**Comment by lf94** [comment]
@padraigfl have you successfully been able to write? Could you share the setup / schematic you're using? I'd greatly appreciate it! I have an ESP8266 I'll be using as well.
