### ISSUE TITLE
Error in README.md regarding Arduino MEGA 2560

### ISSUE THREAD

**Issue by Kreativ2121** [ShendoXT/memcarduino#34]
There is a small error in readme. In the table under "Connecting a Memory Card to Arduino" it is suggested that Command pin should be connected to D52 for Arduino Mega 2560.

In fact, it should be connected to D51. I have noticed that Memcarduino is not working out of the box on Mega and started to look for differences between the UNO and Mega Pinout. In UNO, command is connected to D11, which is a MOSI pin for SPI communication. On Mega, D51 is a MOSI pin. I switched it to D51 and everything works like a charm. :)

**Comment by ShendoXT** [comment]
Awesome that you got it working. Thanks for the heads up, I will change it immediately.
