### ISSUE TITLE
Can't compile for ATmega32u4

### ISSUE THREAD

**Issue by Crx91** [ShendoXT/memcarduino#38]
Hi Shendo,
It seems with the latest release of memcarduino i can't compile the sketch for the platform based on the atmega32u4 like arduino Leonardo...

Error during compiling is:
"Compilation error: 'ushort' was not declared in this scope"

**Comment by ShendoXT** [comment]
And right you are. my bad.

I changed ushort to unsigned short, that should work on all platforms now.
Can you please try with the updated version?
